timezone: "Asia/Seoul"
discord:
  webhook_url: ""
  username: "ServerOpsKit"
  avatar_url: ""
pregen_throttle:
  enabled: true
  avg_window_seconds: 5
  spike_ms: 60
  resume_tps: 18.5
  max_online_to_run: 2
  announce_to_players: true
  use_chunky_quiet: true
  worlds_center_radius:
    world: "0 0 3000"
    world_nether: "0 0 2000"
    world_the_end: "0 0 2000"
spark_trigger:
  enabled: true
  below_tps: 15.0
  duration_seconds: 10
  timeout_seconds: 60
entity_relief:
  enabled: true
  sample_every_ticks: 100
  thresholds:
    items_total: 1200
    mobs_total: 900
  item_cleanup:
    mode: "safe"
    age_seconds_min: 120
    whitelist_ids:
      - "minecraft:nether_star"
      - "minecraft:diamond"
    whitelist_prefixes:
      - "pixelmon:"
  actions:
    message_players: true
    extra_commands: []
backup:
  enabled: true
  hour_minute: "04:30"
  worlds: ["world","world_nether","world_the_end"]
  dir: "backups"
  keep_max: 14
autorestart:
  enabled: true
  check_every_seconds: 30
  heap_usage_percent_threshold: 90
  sustain_seconds: 180
  warn_minutes: [5, 1]
  restart_command: "restart"
logwatch:
  enabled: true
  latest_log_path: "logs/latest.log"
