world-name: world

trash:
  gui-title: "쓰레기통"
  size: 54

optimize:
  default-tool: chunky
  chunky:
    start: ["chunky world {world}", "chunky center 0 0", "chunky radius {radius}", "chunky pattern square", "chunky start"]
    pause: ["chunky pause"]
    status: ["chunky status"]
  worldborder:
    # 아래는 콘솔 명령 템플릿 (원하면 사용). WB 자동화는 기본적으로 'API' 사용.
    start: ["worldborder center 0 0", "worldborder set {diameter}"]
    pause: []
    status: []
  starlight:
    relight: ["starlight relight {world}"]

farm_protect:
  enabled: true

cleanup:
  worlds: ["world"]
  announce_seconds: [30, 10, 5, 4, 3, 2, 1]
  default_seconds: 30
  message_template: "&e{world}&7 월드에서 {sec}초 후 바닥 아이템을 청소합니다."
  cleared_message: "&a{world}&7 월드 바닥 아이템 {count}개 제거 완료."
  target_entity_types: ["DROPPED_ITEM"]
  auto:
    enabled: true
    interval_minutes: 10
    seconds: 30
    announce_seconds: [30, 10, 5, 4, 3, 2, 1]
    check_conditions: false
    worlds: []   # 비우면 cleanup.worlds 사용

conditions:
  enabled: true
  min_tps: 18.5
  max_players: 4
  time_window:
    enabled: true
    timezone: "Asia/Seoul"
    start_hour: 2
    end_hour: 9

automation:
  enabled: false
  timezone: "Asia/Seoul"
  times: ["02:00","08:00"]    # 매일 이 시각에 트리거
  player_threshold: 30        # 이 인원 '미만'일 때만 수행
  worldborder:
    worlds: ["world"]         # 확장할 월드 목록
    use_api: true             # true면 Bukkit API로 확장(권장), false면 아래 콘솔 명령 템플릿 사용
    start_radius: 5000        # 최초 기준 반경(저장기록 없을 때)
    increment: 5000           # 실행마다 확장량
    max_radius: 200000        # 최대 반경. 도달 시 자동화 종료
    fill_after_set: false     # API 사용 시 무시됨(콘솔 템플릿 쓸 때만 의미)
    trigger_chunky_after_expand: false  # 확장 후 Chunky로 미리 생성
    chunky:
      start: ["chunky world {world}", "chunky center 0 0", "chunky radius {radius}", "chunky pattern square", "chunky start"]
