world-name: bskyblock_world

trash:
  gui-title: "쓰레기통"
  size: 54

optimize:
  default-tool: chunky
  chunky:
    start: ["chunky world {world}", "chunky center 0 0", "chunky radius {radius}", "chunky pattern square", "chunky start"]
    pause: ["chunky pause"]
    status: ["chunky status"]
  worldborder:
    start: ["wb {world} set {radius} spawn", "wb {world} fill"]
    pause: ["wb fill cancel"]
    status: ["wb fill status"]
  starlight:
    relight: ["starlight relight {world}"]

cleanup:
  worlds: ["world", "bskyblock_world"]
  announce_seconds: [30, 10, 3, 2, 1]
  default_seconds: 30
  message_template: "&e{world}&7 월드에서 {sec}초 후 바닥 아이템을 청소합니다."
  cleared_message: "&a{world}&7 월드 바닥 아이템 {count}개 제거 완료."
  target_entity_types: ["DROPPED_ITEM"]

conditions:
  enabled: true
  min_tps: 18.5
  max_players: 4
  time_window:
    enabled: true
    timezone: "Asia/Seoul"
    start_hour: 2
    end_hour: 9
