# UltimateTrashOptimize v1.5.4 - Spigot/CatServer 1.16.5, Java 8
general:
  prefix: "&6[UTO]&r "

messages:
  no_permission: "&c권한이 없습니다."
  not_player: "&c플레이어만 사용할 수 있습니다."
  reloaded: "&a구성이 리로드되었습니다."
  conditions_denied: "&c[조건] 현재 실행 불가: %reason%"
  conditions_allowed: "&a[조건] 현재 실행 허용"
  cleanup_countdown: "&e%world% 월드 청소 %seconds%s 후 실행됩니다..."
  cleanup_started: "&6%world% 월드 청소를 시작합니다."
  cleanup_done: "&a청소 완료: 제거된 엔티티 %count%개"
  pixelmon_cleanup_done: "&bPixelmon 비전설 제거 완료: %count%개 (월드: %world%)"
  automation_started: "&a[WB] 자동화를 시작합니다."
  automation_stopped: "&c[WB] 자동화를 중지했습니다."
  automation_status: "&e[WB] %world% 반경 %radius% / 최대 %max% (드라이런: %dryrun%)"
  farm_protect_on: "&a농장보호 ON"
  farm_protect_off: "&c농장보호 OFF"
  help_header: "&6===== &eUTO 도움말 &6====="
  help_line: "&e/uto %cmd% &7- %desc%"
  version: "&e버전: &f%version%&7, &e서버: &f%server%, &e자바: &f%java%"
  status_tps: "&eTPS(1/5/15s 평균): &a%tps1% / %tps5% / %tps15%"
  status_conditions: "&e조건가드: &a%enabled% &7(이유: %reason%)"
  status_auto: "&e자동청소: &a%enabled% &7(간격: %sec%s)"

trash:
  gui-title: "&8쓰레기통"
  rows: 3
  destroy-on-close: true
  block-shift-click: true
  block-number-key: true
  pdc-key: "uto:trash_key"

conditions:
  enabled: true
  min_tps: 18.5
  max_players: 50
  cooldown_sec: 20
  time_window:
    enabled: true
    timezone: "Asia/Seoul"
    start_hour: 2
    end_hour: 9
  allowed_days: ["MON","TUE","WED","THU","FRI","SAT","SUN"]

tps:
  avg_seconds_short: 1
  avg_seconds_mid: 5
  avg_seconds_long: 15

cleanup:
  ground:
    enabled: true
    ignorePlayerCount: true
    intervalSeconds: 300
    worlds: []
    targetEntityTypes: ["DROPPED_ITEM"]
    countdownSeconds: 10

  entity:
    enabled: true
    worlds: []
    batchPerTick: 200
    excludeEntityTypes: ["PLAYER", "ARMOR_STAND", "ITEM_FRAME", "PAINTING"]

  pixelmon:
    enabled: true
    worlds: []
    intervalSeconds: 600
    skipLegendaries: true
    legendarySpeciesWhitelist: [
      "Articuno","Zapdos","Moltres","Mewtwo","Mew","Raikou","Entei","Suicune","Lugia","Ho-Oh",
      "Celebi","Regirock","Regice","Registeel","Latias","Latios","Kyogre","Groudon","Rayquaza",
      "Jirachi","Deoxys","Uxie","Mesprit","Azelf","Dialga","Palkia","Heatran","Regigigas",
      "Giratina","Cresselia","Darkrai","Shaymin","Arceus","Victini","Cobalion","Terrakion","Virizion",
      "Tornadus","Thundurus","Landorus","Reshiram","Zekrom","Kyurem","Keldeo","Meloetta","Genesect",
      "Xerneas","Yveltal","Zygarde","Diancie","Hoopa","Volcanion","Solgaleo","Lunala","Necrozma",
      "Zacian","Zamazenta","Eternatus"
    ]
    detection:
      classNameContains: ["pixelmon"]
      namePattern: "(?i)(Lvl|Lv\.|\[[0-9]+\])"

automation:
  worldborder:
    enabled: false
    dryRun: false
    player_threshold: 0
    worlds:
      world:
        increment: 100
        max_radius: 10000
        step_seconds: 60

farm:
  protect:
    enabled: true
