name: UltimateTrashOptimize
main: com.minkang.uto.Main
version: 1.6.0
api-version: 1.16
author: minkang
softdepend: [Chunky, WorldBorder, Starlight]

commands:
  trash:
    description: Open trash GUI
    usage: /trash
    aliases: [쓰레기통]
    permission: ultimate.trash.use

  optimize:
    description: Wrapper helpers for Chunky/WorldBorder/Starlight
    usage: /optimize <chunky|worldborder|starlight|all|start> [world]
    aliases: [최적화]
    permission: ultimate.optimize.admin

  cleanup:
    description: Cleanup ground items / general entity cleanup (countdown + batch)
    usage: /cleanup <world> [seconds]
    aliases: [청소]
    permission: ultimate.cleanup.admin

  conditions:
    description: Toggle or set condition guard
    usage: /conditions [on|off]
    aliases: [조건]
    permission: ultimate.conditions.admin

  conditionstatus:
    description: Show current condition guard state and reason
    usage: /conditionstatus
    aliases: [조건상태]
    permission: ultimate.conditions.admin

  automation:
    description: WorldBorder automation control
    usage: /automation <start|stop|status> [world]
    aliases: [자동화]
    permission: ultimate.automation.admin

  farmprotect:
    description: Toggle farmland trampling protection
    usage: /farmprotect [on|off]
    aliases: [농장보호]
    permission: ultimate.farm.admin

  uto:
    description: UTO root command (help/version/status/reload/entityauto)
    usage: /uto <help|version|status|reload|entityauto|pixelmonauto> [args...]
    permission: ultimate.uto

permissions:
  ultimate.trash.use: { default: true, description: Trash GUI use }
  ultimate.trash.admin: { default: op, description: Trash admin }
  ultimate.optimize.admin: { default: op, description: Optimize wrappers }
  ultimate.cleanup.admin: { default: op, description: Run/auto cleanup }
  ultimate.conditions.admin: { default: op, description: Condition guard control }
  ultimate.farm.admin: { default: op, description: Farm protection toggle }
  ultimate.automation.admin: { default: op, description: WorldBorder automation control }
  ultimate.uto: { default: op, description: UTO root command }
