name: UltimateTrashOptimize
main: com.minkang.uto.Main
version: 1.7.0
api-version: 1.16
author: minkang
commands:
  uto:
    description: 리로드/토글/상태
    usage: /uto <reload|status|toggle>
    permission: uto.admin
permissions:
  uto.admin:
    default: op
