name: Build & Release (Java 8)

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:

permissions:
  contents: write   # tag push 시 릴리즈 업로드 위해 필요

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.module }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ "ultimate-autochunky", "serveropskit" ]  # 리포 구조에 맞게 조정 가능
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "8"
          cache: maven

      - name: Build with Maven
        run: |
          mvn -B -q -DskipTests -f "${{ matrix.module }}/pom.xml" clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.module }}-jar
          path: ${{ matrix.module }}/target/*.jar

  release:
    name: Release on tag
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
