name: Java 8 Maven - Auto modules

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "8"
          cache: maven

      - name: Build all Maven modules (auto-discover)
        run: |
          set -e
          mapfile -t POMS < <(git ls-files | grep -E '(^|/)+pom\.xml$' | grep -v '^\.github/')
          echo "Found POMs:"
          printf ' - %s
' "${POMS[@]}"
          for P in "${POMS[@]}"; do
            echo ">>> Building $P"
            mvn -B -q -DskipTests -f "$P" clean package
          done

      - name: Upload all JARs
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: |
            **/target/*.jar
            !**/*-sources.jar
            !**/*-javadoc.jar

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: jars
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
